global: { scrape_interval: 15s }
scrape_configs:
- job_name: 'node'
  static_configs: [
    {targets: ['monitoring-node-exporter-server:9100']} 
  ]

# BỔ SUNG:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090'] # Scrape chính Prometheus để tự giám sát
